@baseUrl = http://localhost:5000/api/customers

# Customer

# @name register new customer
POST {{baseUrl}}/register
Content-Type: application/json

{
    "username": "Boyka",
    "password": "vitcon123",
    "confirmPassword": "vitcon123",
    "phoneNumber": "0961234456",
    "address": "Ha Noi"
}

###
# @name get user
Get {{baseUrl}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mjg2NTQ5MjA4NzZmMzhlYjk1Y2VhZTciLCJ0eXBlIjoiY3VzdG9tZXIiLCJpYXQiOjE2NTY5MjM5MzQsImV4cCI6MTY1NjkyNDgzNH0.TqmW2FVM_1Zle6WohNjyL3NfKfx9GkWt1sjZRnFdwiQ

###
# @name login user
POST {{baseUrl}}/login
Content-Type: application/json

{
    "phoneNumber": "0961234327",
    "password": "vitcon123"
}

###
# @name get new token
POST {{baseUrl}}/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mjg2NTM0MTJhMzFiYWIyM2FhY2QyMzkiLCJ0eXBlIjoiY3VzdG9tZXIiLCJpYXQiOjE2NTI5NzAzNjUsImV4cCI6MTY1MzgzNDM2NX0.dhgHkiEEoh6_qVb8VvQuSOTH6f2wMw9bH4uRJy4hqOA"
}

### @name logout 
POST {{baseUrl}}/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mjg2NTM0MTJhMzFiYWIyM2FhY2QyMzkiLCJ0eXBlIjoiY3VzdG9tZXIiLCJpYXQiOjE2NTI5NzAzNjUsImV4cCI6MTY1MzgzNDM2NX0.dhgHkiEEoh6_qVb8VvQuSOTH6f2wMw9bH4uRJy4hqOA"
}

