@baseUrl = http://localhost:5000/api/orders

POST {{baseUrl}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mjg2NTM0MTJhMzFiYWIyM2FhY2QyMzkiLCJ0eXBlIjoiY3VzdG9tZXIiLCJpYXQiOjE2NTQzNTMxMDQsImV4cCI6MTY1NDM1NDAwNH0.mil_-1bengyHYThEvzbALAYv-jz7yviqBoXTYoA3o5I
Content-Type: application/json

{
    "comments": "Many sugar",
    "products": [{
        "productId": "62838a6dc63bc7dc6c04176a",
        "price": 200,
        "quantity": 1
    }]
}

###
GET {{baseUrl}}/customer