@baseUrl = http://localhost:5000/api/product-category

# @name create 
POST {{baseUrl}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjgyMDY3ZjdlZWRhMmNmZDkyYTQ1YWMiLCJ0eXBlIjoiY3VzdG9tZXIiLCJpYXQiOjE2NTI3ODc0NzYsImV4cCI6MTY1Mjc4ODM3Nn0.ZrGHtQ0_T8l5fwSdQqw7VmoprC2b7RniorEdBPN2s3Q
Content-Type: application/json

{
    "name": "Cheese"
}

###
GET {{baseUrl}}

###
GET {{baseUrl}}/62822185506ca3a53c8ad177

###
PUT {{baseUrl}}/62822376f9319c851503e339
Content-Type: application/json

{
    "name": "Vegetable"
}

###
DELETE {{baseUrl}}/62822376f9319c851503e339

