@baseUrl = http://localhost:5000/api/products

# @name get list of products
GET {{baseUrl}}?name_like=xa

###
DELETE {{baseUrl}}/628389d3e2c6fbbe33da07f5

###
GET {{baseUrl}}/ca-phe-cacao-chanh

###
GET {{baseUrl}}/62838a6dc63bc7dc6c04176a/edit

###
PATCH {{baseUrl}}/62838a6dc63bc7dc6c04176a/restore

###
PUT {{baseUrl}}/62838a6dc63bc7dc6c04176a
Content-Type: application/json

{
    "name": "Cà phê cacao chanh xa",
    "price": 100,
    "priceDiscount": 50,
    "status": "Hot",
    "type": "628389b8e2c6fbbe33da07f3"
}

###
POST {{baseUrl}}
Content-Type: application/json

{
    "name": "Cà phê cacao chanh xa",
    "price": 100,
    "priceDiscount": 50,
    "status": "Hot",
    "type": "628389b8e2c6fbbe33da07f3"
}